{
 "title": "powerstore_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   { "name": "powerstore", "label": "PowerStore", "query": "fnm0876" },
   {
    "name": "instance",
    "label": "Exporter",
    "query": "label_values(up{job=\"$job\",powerstore=\"$powerstore\"},instance)"
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": "label_values(cluster_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\"}, name)"
   },
   {
    "name": "appliance_name",
    "label": "Appliance",
    "query": "label_values(appliance_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\"}, name)"
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": "label_values(node_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\"},name)"
   },
   {
    "name": "fc_name",
    "label": "FC Port",
    "query": "label_values(fc_port_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\"},name)"
   },
   {
    "name": "eth_name",
    "label": "Eth Port",
    "query": "label_values(eth_port_avg_pkt_tx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\"},name)"
   },
   {
    "name": "vol_name",
    "label": "Volume Name",
    "query": "label_values(volume_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\"},name)"
   },
   {
    "name": "fs_name",
    "label": "FS Name",
    "query": "label_values(file_system_avg_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "content": "\n# About\n\nThis is the sample dashboard for PowerStore with \"rollup\" as true. For \"rollup\" as false, the metrics are different, please define a new dashboard with the supported metrics like this sample.\n\n**Notes**: when there are a large num. of volumes or file systems, it is recommended to select just a few instead of all since the dashboard needs more time to render diagrams which eats CPU and memory at the browser side that lead to computer slow response.\n\n# Prometheus Configuration\n\nA unique label named \"powerstore\" needs to be assigned for each monitored PowerStore. The label value will be used to filter PowerStore arrays.\n\n\n```\n- job_name: 'powerstore_exporter'\n  static_configs:\n    - targets:\n        - 192.168.10.10:9100\n      labels:\n        powerstore: fnm1010\n```\n\n"
  },
  {
   "title": "Appliance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "I/O Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "appliance_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$appliance_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "appliance_max_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=\"$appliance_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "node_avg_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "node_avg_unaligned_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "node_max_unaligned_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "node_avg_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "node_avg_unaligned_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "node_max_unaligned_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "node_avg_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "node_avg_unaligned_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "node_max_unaligned_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "node_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "node_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "node_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node_avg_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "node_avg_unaligned_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "node_max_unaligned_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Read Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node_avg_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "node_avg_unaligned_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "node_max_unaligned_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Write Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node_avg_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "node_avg_unaligned_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "node_max_unaligned_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "I/O Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "node_max_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$node_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    }
   ]
  },
  {
   "title": "FC Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "fc_port_avg_unaligned_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "fc_port_max_unaligned_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "fc_port_avg_unaligned_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "fc_port_max_unaligned_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "fc_port_avg_unaligned_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "fc_port_max_unaligned_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "fc_port_avg_unaligned_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "fc_port_max_unaligned_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Read Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "fc_port_avg_unaligned_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "fc_port_max_unaligned_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "Write Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      },
      {
       "expr": "fc_port_avg_unaligned_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg Unaligned"
      },
      {
       "expr": "fc_port_max_unaligned_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max Unaligned"
      }
     ]
    },
    {
     "title": "I/O Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 108 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Current Login",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_current_logins{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_current_logins{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Frame Dumped",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_dumped_frames_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_dumped_frames_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Signal Loss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 116 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_loss_of_signal_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_loss_of_sync_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Sync Loss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_loss_of_sync_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_loss_of_sync_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Invalid CRC",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_invalid_crc_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_invalid_crc_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Invalid Tx Word",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_invalid_tx_word_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_invalid_tx_word_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Sequence Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_prim_seq_prot_err_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_prim_seq_prot_err_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Link Failure",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "fc_port_avg_link_failure_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "fc_port_max_link_failure_count_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fc_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethernet Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput Avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "eth_port_avg_bytes_rx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Rx"
      },
      {
       "expr": "eth_port_avg_bytes_tx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Tx"
      }
     ]
    },
    {
     "title": "Package Delivered Avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 141 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "eth_port_avg_pkt_rx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Rx"
      },
      {
       "expr": "eth_port_avg_pkt_tx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Tx"
      }
     ]
    },
    {
     "title": "Package Delivered Tx Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 141 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "eth_port_avg_pkt_tx_error_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "eth_port_max_pkt_tx_error_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Throughput Max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "eth_port_max_bytes_rx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Rx"
      },
      {
       "expr": "eth_port_max_bytes_tx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Tx"
      }
     ]
    },
    {
     "title": "Package Delivered Max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 149 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "eth_port_max_pkt_rx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Rx"
      },
      {
       "expr": "eth_port_max_pkt_tx_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Tx"
      }
     ]
    },
    {
     "title": "Package Delivered CRC Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 149 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "eth_port_avg_pkt_rx_crc_error_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "eth_port_max_pkt_rx_crc_error_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Package Delivered No Buffer Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 157 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "eth_port_avg_pkt_rx_no_buffer_error_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "eth_port_max_pkt_rx_no_buffer_error_ps{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$eth_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "volume_avg_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "volume_avg_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "volume_avg_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "volume_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "volume_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "volume_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "volume_avg_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "volume_avg_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "volume_avg_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "I/O Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "volume_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_avg_io_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "volume_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "volume_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "volume_max_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$vol_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_total_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_read_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_write_iops{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_avg_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_avg_read_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_avg_write_latency{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_total_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_read_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_write_bandwidth{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "I/O Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_avg_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Read Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_avg_read_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    },
    {
     "title": "Write Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "file_system_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Avg"
      },
      {
       "expr": "file_system_max_avg_write_size{job=\"$job\",instance=\"$instance\",powerstore=\"$powerstore\",name=~\"$fs_name\"}",
       "legendFormat": "{{name}} Max"
      }
     ]
    }
   ]
  }
 ]
}